openapi: 3.0.3
info:
  title: Order Service API
  description: Microservice de gestion des commandes
  version: 1.0.0

servers:
  - url: http://localhost:8083
    description: Order Service

tags:
  - name: Orders
    description: Order management

paths:

  /api/v1/orders:
    get:
      tags: [Orders]
      summary: List all orders
      responses:
        '200':
          description: List of orders
    post:
      tags: [Orders]
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
      responses:
        '201':
          description: Order created

  /api/v1/orders/{id}:
    get:
      tags: [Orders]
      summary: Get order by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Order details
    delete:
      tags: [Orders]
      summary: Cancel an order
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Order cancelled

  /api/v1/orders/{id}/status:
    put:
      tags: [Orders]
      summary: Update order status
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [status]
              properties:
                status:
                  type: string
                  enum: [PENDING, CONFIRMED, SHIPPED, DELIVERED, CANCELLED]
      responses:
        '200':
          description: Status updated

  /api/v1/orders/user/{userId}:
    get:
      tags: [Orders]
      summary: Get orders by user
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Orders for user

  /api/v1/orders/status/{status}:
    get:
      tags: [Orders]
      summary: Get orders by status
      parameters:
        - in: path
          name: status
          required: true
          schema:
            type: string
            enum: [PENDING, CONFIRMED, SHIPPED, DELIVERED, CANCELLED]
      responses:
        '200':
          description: Orders by status

components:
  schemas:

    OrderRequest:
      type: object
      required: [userId, shippingAddress, items]
      properties:
        userId:
          type: integer
        shippingAddress:
          type: string
        items:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/OrderItemRequest'

    OrderItemRequest:
      type: object
      required: [productId, quantity]
      properties:
        productId:
          type: integer
        quantity:
          type: integer
          minimum: 1